# Generated by Django 5.1 on 2025-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassic_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nourriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Viandes', 'Viandes'), ('Proie', 'Proie'), ('Poisson', 'Poisson'), ('Requin', 'Requin'), ('Fibre au ras du sol', 'Fibre au ras du sol'), ('Fruit au ras du sol', 'Fruit au ras du sol'), ('Fibre en hauteur', 'Fibre en hauteur'), ('Fruit en hauteur', 'Fruit en hauteur'), ('Feuille au ras du sol', 'Feuille au ras du sol'), ('Feuille en hauteur', 'Feuille en hauteur'), ('Noix au ras du sol', 'Noix au ras du sol'), ('Noix en hauteur', 'Noix en hauteur')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dinosaure',
            name='regime_alimentaire',
        ),
        migrations.AlterField(
            model_name='dinosaure',
            name='aime',
            field=models.ManyToManyField(blank=True, related_name='aime_par', to='jurassic_site.dinosaure'),
        ),
        migrations.AlterField(
            model_name='dinosaure',
            name='naime_pas',
            field=models.ManyToManyField(blank=True, related_name='naime_pas_par', to='jurassic_site.dinosaure'),
        ),
        migrations.AlterField(
            model_name='dinosaure',
            name='type',
            field=models.CharField(choices=[('Herbivore', 'Herbivore'), ('Carnivore', 'Carnivore'), ('Piscivore', 'Piscivore'), ('Reptile marin', 'Reptile marin'), ('Reptile volant', 'Reptile volant')], max_length=50),
        ),
        migrations.AddField(
            model_name='dinosaure',
            name='nourriture',
            field=models.ManyToManyField(blank=True, to='jurassic_site.nourriture'),
        ),
        migrations.DeleteModel(
            name='Regime',
        ),
    ]
