# Generated by Django 5.1 on 2025-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassic_site', '0003_alter_dinosaure_aime_alter_dinosaure_naime_pas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nourriture',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
