# Generated by Django 5.1 on 2025-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassic_site', '0004_alter_nourriture_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaure',
            name='type',
            field=models.CharField(choices=[('Herbivore', 'Herbivore'), ('Carnivore', 'Carnivore'), ('Piscivore', 'Piscivore'), ('Reptile marin', 'Reptile marin'), ('Reptile volant', 'Reptile volant')], max_length=50),
        ),
    ]
