# Generated by Django 5.1 on 2025-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassic_site', '0005_alter_dinosaure_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinosaure',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Dinosaures'},
        ),
        migrations.AlterModelOptions(
            name='nourriture',
            options={'verbose_name_plural': 'Nourritures'},
        ),
        migrations.AddField(
            model_name='dinosaure',
            name='naime_pas_familles',
            field=models.CharField(blank=True, help_text='Familles incompatibles (séparées par des virgules)', max_length=200),
        ),
        migrations.AddField(
            model_name='dinosaure',
            name='naime_pas_types',
            field=models.CharField(blank=True, help_text='Types incompatibles (séparés par des virgules)', max_length=200),
        ),
        migrations.AlterField(
            model_name='dinosaure',
            name='famille',
            field=models.CharField(choices=[('Sauropodes', 'Sauropodes'), ('Pachycéphalosauridé', 'Pachycéphalosauridé'), ('Hadrosauridé', 'Hadrosauridé'), ('Ankylosauridé', 'Ankylosauridé'), ('Cératopsien', 'Cératopsien'), ('Ornithomimosaurien', 'Ornithomimosaurien'), ('Théropode', 'Théropode'), ('Stégosauridé', 'Stégosauridé'), ('Ptérosaure', 'Ptérosaure'), ('Mosasauridé', 'Mosasauridé'), ('Plésiosaure', 'Plésiosaure')], max_length=100),
        ),
    ]
