# Generated by Django 5.1 on 2025-12-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassic_site', '0006_alter_dinosaure_options_alter_nourriture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaure',
            name='famille',
            field=models.CharField(blank=True, choices=[('Sauropodes', 'Sauropodes'), ('Pachycéphalosauridé', 'Pachycéphalosauridé'), ('Hadrosauridé', 'Hadrosauridé'), ('Ankylosauridé', 'Ankylosauridé'), ('Cératopsien', 'Cératopsien'), ('Ornithomimosaurien', 'Ornithomimosaurien'), ('Charognard', 'Charognard'), ('Hybrides', 'Hybrides')], max_length=100, null=True),
        ),
    ]
