# Generated by Django 5.1 on 2025-12-15 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurassic_site', '0007_alter_dinosaure_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaure',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
